name: cpr_training_app
description: Smart Interactive CPR Training Application for medical training purposes only.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^4.0.2
  flutter_tts: ^4.0.2

  # Add these packages for storage and audio playback
  shared_preferences: ^2.3.2
  audioplayers: ^6.0.0
